#!/usr/bin/env python3
#
# mkresfs.py - build the ResourceFS file chain the graphics card's ROM carries
#
# Copyright (C) 2026 Andy Timmins
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# The driver registers this chain with ResourceFS at initialisation, which puts
# the application in Resources:$.Apps.!GfxCard - out of the card's own ROM, so
# nothing is installed on a disc and it is present exactly when the card is.
#
# Every file in this directory whose name carries a RISC OS filetype suffix
# (!Sprites,ff9 / Templates,fec / Messages,fff and so on) is picked up and
# embedded automatically: drop a file in and it appears in the application
# directory, with no change to the assembler or the Makefile. Sources have no
# suffix, so there is nothing to exclude.
#
# A file under one of the conventional names an application always carries is
# taken even without a suffix, because its type is not in doubt: a file called
# Messages is text and a file called Templates is a template file, however it
# arrived here from RISC OS.
#
# The format is the one ResourceFS documents: per file, an offset to the next
# entry, the load and exec addresses and size as OS_File would give them, the
# attributes, the name without "$.", then (word-aligned) the size again plus
# four, then the data. A single zero word ends the list.

import os
import re
import sys

APP = "Apps.!GfxCard"		# where the files appear under Resources:$
ATTR = 3			# read/write, as ROM files are
TYPE_OBEY = 0xFEB
TYPE_ABS = 0xFF8
TYPE_TEXT = 0xFFF
TYPE_SPRITE = 0xFF9
TYPE_TEMPLATE = 0xFEC

# Names that need no suffix: the type follows from the name.
KNOWN = {
    "!Boot": TYPE_OBEY,
    "!Help": TYPE_TEXT,
    "!Run": TYPE_OBEY,
    "!Sprites": TYPE_SPRITE,
    "!Sprites22": TYPE_SPRITE,
    "Messages": TYPE_TEXT,
    "Templates": TYPE_TEMPLATE,
}

# The application itself: a build product rather than a file dropped in here.
RUNIMAGE = "gfxapp"

# Build products that happen to carry a filetype suffix. Without this the module's
# own ROM image is picked up and embedded inside itself, which doubles its size.
EXCLUDE = {"RPCEmuGfx,ffa"}

# Used when no !Run has been provided. Sets a slot big enough for the
# application and its stack, then runs it.
DEFAULT_RUN = (
    "| The graphics card's own utility, out of the card's ROM.\n"
    "WimpSlot -min 64k -max 64k\n"
    "Run <Obey$Dir>.!RunImage\n"
)

SUFFIX = re.compile(r"^(?P<name>.+),(?P<type>[0-9a-fA-F]{3})$")


def load_address(filetype):
    """The load address OS_File would report for a file of this type."""
    return 0xFFF00000 | ((filetype & 0xFFF) << 8)


def asm_label(name):
    """A label safe for the assembler, derived from a RISC OS leaf name."""
    return "rf_" + re.sub(r"[^A-Za-z0-9]", "_", name).lower()


def collect(directory):
    """Every resource file here, sorted so the build is reproducible."""
    found = []
    for entry in sorted(os.listdir(directory)):
        path = os.path.join(directory, entry)
        if not os.path.isfile(path):
            continue
        if entry in EXCLUDE:
            continue
        m = SUFFIX.match(entry)
        if m is not None:
            found.append((m.group("name"), int(m.group("type"), 16), entry))
        elif entry in KNOWN:
            found.append((entry, KNOWN[entry], entry))
    return found


def main():
    directory = sys.argv[1] if len(sys.argv) > 1 else "."
    out_path = sys.argv[2] if len(sys.argv) > 2 else "resfs.inc"

    dropped = collect(directory)
    have_run = any(name == "!Run" for name, _, _ in dropped)

    lines = [
        "@ Generated by mkresfs.py - do not edit.",
        "@",
        "@ The application directory the driver registers with ResourceFS. Every file",
        "@ in riscos-progs/RPCEmuGfx with a filetype suffix is here automatically.",
        "",
        "\tATTR_READ\t= %d" % ATTR,
        "",
        "resfs_files:",
    ]

    # Each entry needs to know where the next one starts, so build the list of
    # labels first and refer forward.
    entries = []
    if not have_run:
        entries.append(("!Run", TYPE_OBEY, None))	# None => the default text
    for name, filetype, filename in dropped:
        entries.append((name, filetype, filename))
    entries.append(("!RunImage", TYPE_ABS, RUNIMAGE))

    labels = [asm_label(name) for name, _, _ in entries]
    labels.append("rf_end")

    for i, (name, filetype, filename) in enumerate(entries):
        label, nxt = labels[i], labels[i + 1]
        data_label = label + "_data"
        end_label = label + "_end"

        lines += [
            "",
            "%s:" % label,
            "\t.int\t%s - %s" % (nxt, label),
            "\t.int\t0x%08x\t\t@ filetype &%03X" % (load_address(filetype), filetype),
            "\t.int\t0",
            "\t.int\t%s - %s" % (end_label, data_label),
            "\t.int\tATTR_READ",
            "\t.string\t\"%s.%s\"" % (APP, name),
            "\t.balign\t4, 0",
            "\t.int\t%s - %s + 4" % (end_label, data_label),
            "%s:" % data_label,
        ]
        if filename is None:
            for text_line in DEFAULT_RUN.splitlines():
                lines.append("\t.ascii\t\"%s\\n\"" % text_line.replace('"', '\\"'))
        else:
            lines.append("\t.incbin\t\"%s\"" % filename)
        lines += ["%s:" % end_label, "\t.balign\t4, 0"]

    lines += ["", "rf_end:", "\t.int\t0\t\t\t@ end of the list", ""]

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print("resfs.inc: %s" % ", ".join(name for name, _, _ in entries))


if __name__ == "__main__":
    main()
