/*
 * The 68000 core that goes in the OPEN Bus co-processor card.
 *
 * ★ WHAT THIS TEST IS FOR, given that tests/test_68000_vectors.c drives thousands
 * of published per-instruction vectors and will always cover the instruction set
 * better than anything written by hand.
 *
 * It covers what vectors structurally cannot see:
 *
 *   - THE DISPATCH TABLE ITSELF. It is generated from the encoding rules, so the
 *     properties worth checking are properties of the generation: that no
 *     encoding was claimed twice, that the encodings which are not instructions
 *     have no handler, and that the ones which are do. A vector suite only ever
 *     exercises encodings somebody thought to generate a vector for; it says
 *     nothing about an encoding wrongly claimed by the wrong group.
 *   - PRIVILEGE AND THE EXCEPTION MODEL end to end: a user-mode program refused
 *     the status register, an exception switching stacks, RTE coming back.
 *   - THE STALL-AND-RETRY PATH, including a resumed MOVEM, which is this core's
 *     one departure from whole-instruction retry.
 *   - The deliberate divergences, which no vector suite would agree with: an
 *     uninstalled vector faulting rather than jumping to address 0.
 *
 * Programs live at &1000, leaving the vector table at the bottom of memory alone.
 */

#include <stdio.h>
#include <string.h>

#include "cpu_68000.h"

/* Not in the public header: the table's own integrity is not a runtime concern,
   but it is exactly what this test exists to check. */
int m68k_table_clashes(void);
extern void (*m68k_handlers[0x10000])(cpu68000_state *s, uint16_t op);
extern uint8_t m68k_base_cycles[0x10000];

static int failures;

static void
check(const char *what, int ok)
{
	printf("  %-66s %s\n", what, ok ? "ok" : "FAIL");
	if (!ok) {
		failures++;
	}
}

static void
check_u32(const char *what, uint32_t got, uint32_t want)
{
	const int ok = (got == want);

	printf("  %-66s %s\n", what, ok ? "ok" : "FAIL");
	if (!ok) {
		printf("      got 0x%08x, wanted 0x%08x\n", got, want);
		failures++;
	}
}

#define RAM_SIZE	0x100000	/* a megabyte, the card's default */
#define PROG_BASE	0x1000

static uint8_t ram[RAM_SIZE];
static cpu68000_state cpu;

/* Programs are written as 16-bit words, which is how a 68000 is assembled. */
static void
load(const uint16_t *prog, unsigned words)
{
	unsigned i;

	memset(ram, 0, sizeof(ram));
	for (i = 0; i < words; i++) {
		ram[PROG_BASE + i * 2] = (uint8_t) (prog[i] >> 8);
		ram[PROG_BASE + i * 2 + 1] = (uint8_t) prog[i];
	}
	cpu68000_init(&cpu, ram, RAM_SIZE);
	cpu68000_reset(&cpu, PROG_BASE);
}

static void
put32(uint32_t at, uint32_t val)
{
	ram[at] = (uint8_t) (val >> 24);
	ram[at + 1] = (uint8_t) (val >> 16);
	ram[at + 2] = (uint8_t) (val >> 8);
	ram[at + 3] = (uint8_t) val;
}

static uint32_t
get32(uint32_t at)
{
	return ((uint32_t) ram[at] << 24) | ((uint32_t) ram[at + 1] << 16) |
	       ((uint32_t) ram[at + 2] << 8) | ram[at + 3];
}

/** Install a handler address for a vector, so an exception has somewhere to go. */
static void
put_vector(unsigned vector, uint32_t handler)
{
	put32(vector * 4u, handler);
}

/*
 * ★ FLAGS MUST BE CHECKED WITHOUT RUNNING THE STOP.
 *
 * STOP loads the whole status register, so ending a program with STOP #&2700
 * wipes the condition codes the test was about to look at - on real hardware as
 * much as here. Every check on a flag therefore steps a known number of
 * instructions instead of running to the end. Twelve checks in the first draft of
 * this file failed for exactly that reason and none of them was the core's fault.
 */
static void
step_n(int n)
{
	int i;

	for (i = 0; i < n; i++) {
		(void) cpu68000_step(&cpu);
	}
}

static int
flag(uint16_t bit)
{
	return (cpu.sr & bit) != 0;
}

static int
run_to_stop(void)
{
	int slices;

	for (slices = 0; slices < 1000; slices++) {
		if (cpu68000_run(&cpu, 1000) == 0) {
			return 1;
		}
	}
	return 0;
}

/* STOP #imm, which is how a program on this card finishes. */
#define STOP_2700	0x4e72u, 0x2700u

/* ------------------------------------------------------------- the table */

/*
 * ★ THE TABLE IS THE POINT OF THE DESIGN, so it is the first thing checked.
 *
 * The decode is generated by asking, of all 65,536 encodings, what each one is.
 * The failure that design is meant to prevent is one group's install claiming
 * encodings that belong to another - and because a claim is refused rather than
 * overwritten, the count of refusals is the whole answer.
 */
static void
test_table(void)
{
	unsigned valid = 0;
	uint32_t op;

	printf("The generated dispatch table:\n");

	load((const uint16_t[]){ STOP_2700 }, 2);

	check("no encoding was claimed by two instructions",
	      m68k_table_clashes() == 0);

	for (op = 0; op < 0x10000u; op++) {
		if (m68k_handlers[op] != NULL) {
			valid++;
		}
	}
	/* Not an exact figure to defend: what matters is that it is a large
	   fraction of the space and not, through some install being wrong, all of
	   it or almost none. */
	check("a plausible number of encodings are instructions",
	      valid > 30000u && valid < 60000u);
	printf("      %u of 65536 encodings decode\n", valid);

	check("every instruction has a cost",
	      m68k_base_cycles[0x4e71u] != 0);

	/*
	 * ★ Encodings that are NOT instructions, each for its own reason. These
	 * are the ones a loose mask would have swallowed.
	 */
	/* &1040 is a byte MOVE whose destination mode is 001, an address
	   register: MOVEA takes word and long only, so this is not an
	   instruction. &1080, one bit along, IS one - MOVE.B D0,(A0) - which is
	   the sort of neighbour a loose mask swallows. */
	check("a byte may not be moved into an address register",
	      m68k_handlers[0x1040u] == NULL);
	check("but MOVE.B D0,(A0) beside it is an instruction",
	      m68k_handlers[0x1080u] != NULL);
	check("MOVEM cannot name a register directly, those being EXT",
	      m68k_handlers[0x4880u] != NULL &&
	      m68k_handlers[0x4880u] == m68k_handlers[0x4887u]);
	check("mode 7 register 5 is not an addressing mode",
	      m68k_handlers[0x4e7du] == NULL);
	check("&4AFC is ILLEGAL and does decode", m68k_handlers[0x4afcu] != NULL);
	check("an &Axxx opcode is not an instruction",
	      m68k_handlers[0xa000u] == NULL);
	check("nor an &Fxxx one", m68k_handlers[0xf000u] == NULL);
}

/* --------------------------------------------------------- running things */

static void
test_moves(void)
{
	printf("\nMoving data about:\n");

	{
		/* MOVEQ #42,D0 : MOVE.L D0,D1 : STOP */
		static const uint16_t prog[] = {
			0x7000u | 42u,		/* MOVEQ #42,D0 */
			0x2200u,		/* MOVE.L D0,D1 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		check("it stops", run_to_stop());
		check("halted rather than faulted", cpu.halted && !cpu.faulted);
		check_u32("MOVEQ loaded a small constant", cpu.d[0], 42);
		check_u32("and MOVE.L copied it", cpu.d[1], 42);
		check_u32("D0 is the exit code", cpu.exit_code, 42);
	}

	{
		/* MOVEQ sign-extends its byte across the whole register. */
		static const uint16_t prog[] = { 0x70ffu, STOP_2700 };

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("MOVEQ #-1 fills the register", cpu.d[0], 0xffffffffu);
	}

	{
		/*
		 * ★ A byte move into a data register changes eight bits; the same
		 * move into an ADDRESS register sign-extends across all 32. That
		 * is one of the two places the register files genuinely differ,
		 * and getting it wrong makes pointer arithmetic fail a long way
		 * from here.
		 */
		static const uint16_t prog[] = {
			0x203cu, 0x0000u, 0xffffu,	/* MOVE.L #&ffff,D0 */
			0x1200u,			/* MOVE.B D0,D1 */
			0x327cu, 0xfffeu,		/* MOVEA.W #-2,A1 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		cpu.d[1] = 0xaaaaaaaau;
		(void) run_to_stop();
		check_u32("a byte into a data register leaves the rest alone",
		          cpu.d[1], 0xaaaaaaffu);
		check_u32("a word into an address register sign-extends",
		          cpu.a[1], 0xfffffffeu);
	}

	{
		/* Big-endian in memory, and a long round trip through it. */
		static const uint16_t prog[] = {
			0x203cu, 0x1234u, 0x5678u,	/* MOVE.L #&12345678,D0 */
			0x23c0u, 0x0000u, 0x2000u,	/* MOVE.L D0,&2000 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("a long store is big-endian", get32(0x2000), 0x12345678u);
		check_u32("its first byte is the most significant", ram[0x2000],
		          0x12);
	}
}

static void
test_arithmetic(void)
{
	printf("\nArithmetic, and the flags nobody gets right first time:\n");

	{
		static const uint16_t prog[] = {
			0x7005u,			/* MOVEQ #5,D0 */
			0x7203u,			/* MOVEQ #3,D1 */
			0xd041u,			/* ADD.W D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("ADD adds", cpu.d[0], 8);
	}

	{
		static const uint16_t prog[] = {
			0x7005u,
			0x7203u,
			0x9041u,			/* SUB.W D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("SUB subtracts", cpu.d[0], 2);
		check("and does not borrow here",
		      (cpu.sr & CPU68000_FLAG_C) == 0);
	}

	{
		/* ★ Carry after a subtraction is a borrow, as on the Motorola
		   8-bits and unlike the 6502. */
		static const uint16_t prog[] = {
			0x7003u,
			0x7205u,
			0x9041u,			/* SUB.W D1,D0 : 3 - 5 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(3);
		check_u32("a subtraction that wraps", cpu.d[0] & 0xffffu, 0xfffeu);
		check("sets carry, meaning it borrowed", flag(CPU68000_FLAG_C));
		check("and the extend bit with it", flag(CPU68000_FLAG_X));
	}

	{
		/* Overflow on a word add: &4000 + &4000 crosses the sign. */
		static const uint16_t prog[] = {
			0x303cu, 0x4000u,		/* MOVE.W #&4000,D0 */
			0x323cu, 0x4000u,		/* MOVE.W #&4000,D1 */
			0xd041u,			/* ADD.W D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(3);
		check_u32("the sum wraps into the sign bit", cpu.d[0] & 0xffffu,
		          0x8000u);
		check("and V says so", flag(CPU68000_FLAG_V));
		check("while C does not", !flag(CPU68000_FLAG_C));
	}

	{
		/* ★ ADDQ on an address register changes no flag at all. */
		static const uint16_t prog[] = {
			0x0c40u, 0x0000u,		/* CMPI.W #0,D0 : sets Z */
			0x5248u,			/* ADDQ.W #1,A0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(2);
		check_u32("ADDQ moved the address register", cpu.a[0], 1);
		check("★ and left the flags from the comparison alone",
		      flag(CPU68000_FLAG_Z));
	}

	{
		static const uint16_t prog[] = {
			0x700cu,			/* MOVEQ #12,D0 */
			0x720cu,			/* MOVEQ #12,D1 */
			0xc0c1u,			/* MULU D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("MULU multiplies into a long", cpu.d[0], 144);
	}

	{
		static const uint16_t prog[] = {
			0x203cu, 0x0000u, 0x0090u,	/* MOVE.L #144,D0 */
			0x720cu,			/* MOVEQ #12,D1 */
			0x80c1u,			/* DIVU D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("DIVU puts the quotient in the low half",
		          cpu.d[0] & 0xffffu, 12);
		check_u32("and the remainder in the high half", cpu.d[0] >> 16, 0);
	}

	{
		/*
		 * ★ Dividing by zero is an exception, not an answer.
		 *
		 * The stack pointer has to be set first, and that is not test
		 * scaffolding: an exception pushes a frame, so a core whose
		 * supervisor stack points at nothing cannot take one. The first
		 * draft of this omitted it and got a DOUBLE FAULT, which is
		 * exactly right - the frame's own push failed - and is what a
		 * real 68000 does when its stack is not set up.
		 */
		static const uint16_t prog[] = {
			0x2e7cu, 0x0000u, 0x8000u,	/* MOVEA.L #&8000,A7 */
			0x7001u,			/* MOVEQ #1,D0 */
			0x7200u,			/* MOVEQ #0,D1 */
			0x80c1u,			/* DIVU D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		put_vector(CPU68000_VEC_DIV_ZERO, 0x3000);
		ram[0x3000] = 0x4e;		/* the handler: STOP #&2700 */
		ram[0x3001] = 0x72;
		ram[0x3002] = 0x27;
		ram[0x3003] = 0x00;
		(void) run_to_stop();
		check("dividing by zero takes its exception",
		      cpu.halted && !cpu.faulted);
		check_u32("through the handler", cpu.pc, 0x3004);
		check_u32("having pushed a six-byte frame", 0x8000u - cpu.a[7], 6);
	}

	{
		/* And with no handler installed it faults, naming the vector,
		   rather than jumping to whatever is at address zero. */
		static const uint16_t prog[] = {
			0x2e7cu, 0x0000u, 0x8000u,	/* MOVEA.L #&8000,A7 */
			0x7001u,
			0x7200u,
			0x80c1u,			/* DIVU D1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check("★ an uninstalled vector faults rather than jumping",
		      cpu.faulted &&
		      cpu.fault_cause == CPU68000_FAULT_NO_HANDLER);
		check_u32("and says which vector had no handler", cpu.fault_addr,
		          CPU68000_VEC_DIV_ZERO);
	}
}

static void
test_shifts_and_bits(void)
{
	printf("\nShifts, and the overflow rule that is unlike the others:\n");

	{
		static const uint16_t prog[] = {
			0x7001u,			/* MOVEQ #1,D0 */
			0xe580u,			/* ASL.L #2,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("ASL shifts left by its count", cpu.d[0], 4);
	}

	{
		/*
		 * ★ ASL's V is set if the sign changed AT ANY POINT, not merely
		 * between the value going in and the answer coming out. &C0
		 * shifted left twice is &00 in a byte: negative, then positive,
		 * then zero - so V is set even though neither end is negative.
		 * A core that compared only the ends would miss it.
		 */
		static const uint16_t prog[] = {
			0x103cu, 0x00c0u,		/* MOVE.B #&c0,D0 */
			0xe500u,			/* ASL.B #2,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(2);
		check_u32("the byte shifted out entirely", cpu.d[0] & 0xffu, 0);
		check("★ and V reports that the sign changed on the way",
		      flag(CPU68000_FLAG_V));
	}

	{
		static const uint16_t prog[] = {
			0x103cu, 0x0081u,		/* MOVE.B #&81,D0 */
			0xe208u,			/* LSR.B #1,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(2);
		check_u32("LSR shifts right", cpu.d[0] & 0xffu, 0x40);
		check("carrying the bottom bit out", flag(CPU68000_FLAG_C));
	}

	printf("\nBit operations, whose size depends on where the operand is:\n");

	{
		/* On a data register the bit number is modulo 32. */
		static const uint16_t prog[] = {
			0x7000u,			/* MOVEQ #0,D0 */
			0x08c0u, 0x001fu,		/* BSET #31,D0 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(2);
		check_u32("BSET reaches bit 31 of a register", cpu.d[0],
		          0x80000000u);
		check("and Z reports the bit was clear before",
		      flag(CPU68000_FLAG_Z));
	}

	{
		/* ★ In memory the operand is a byte, so the number is modulo 8. */
		static const uint16_t prog[] = {
			0x08f9u, 0x0009u, 0x0000u, 0x2000u, /* BSET #9,&2000 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("★ a bit number in memory wraps at 8, so 9 means 1",
		          ram[0x2000], 0x02);
	}
}

static void
test_branches(void)
{
	printf("\nBranches and loops:\n");

	{
		/* A counted loop with DBRA, which is DBcc with a false condition. */
		static const uint16_t prog[] = {
			0x7000u,			/* MOVEQ #0,D0 */
			0x323cu, 0x0009u,		/* MOVE.W #9,D1 */
			0x5240u,			/* ADDQ.W #1,D0 */
			0x51c9u, 0xfffcu,		/* DBRA D1,-4 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		check("the loop ends", run_to_stop());
		check_u32("★ DBcc runs count+1 times, testing after decrementing",
		          cpu.d[0], 10);
		check_u32("and leaves the counter at -1", cpu.d[1] & 0xffffu,
		          0xffffu);
	}

	{
		static const uint16_t prog[] = {
			0x7005u,			/* MOVEQ #5,D0 */
			0x0c40u, 0x0005u,		/* CMPI.W #5,D0 */
			0x6702u,			/* BEQ +2 */
			0x7000u,			/* MOVEQ #0,D0 : skipped */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("BEQ skipped the instruction after it", cpu.d[0], 5);
	}

	{
		/* BSR and RTS, and the stack they use. */
		static const uint16_t prog[] = {
			0x2e7cu, 0x0000u, 0x8000u,	/* MOVEA.L #&8000,A7 */
			/* ★ Six, not four: a displacement is measured from the
			   extension word, and the STOP it jumps over is two
			   words. Getting this wrong lands in the middle of an
			   instruction, which decodes as something else entirely
			   rather than failing. */
			0x6100u, 0x0006u,		/* BSR +6 */
			STOP_2700,
			0x7c2au,			/* MOVEQ #42,D6 */
			0x4e75u				/* RTS */
		};

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check_u32("BSR reached the subroutine", cpu.d[6], 42);
		check_u32("and RTS came back, balancing the stack", cpu.a[7],
		          0x8000u);
	}

	{
		/* Scc writes &FF for true, not 1. */
		static const uint16_t prog[] = {
			0x7000u,			/* MOVEQ #0,D0 */
			0x0c40u, 0x0000u,		/* CMPI.W #0,D0 */
			0x57c1u,			/* SEQ D1 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		step_n(3);
		check_u32("Scc writes all ones, not one", cpu.d[1] & 0xffu, 0xff);
	}
}

/*
 * ★ PRIVILEGE, AND STOP'S SECOND HALF.
 *
 * These are the two things that make this core different in kind from the others
 * on this card rather than merely bigger: a program can be refused, and a stopped
 * program can be started again.
 */
static void
test_privilege_and_stop(void)
{
	printf("\nPrivilege, and the two halves of STOP:\n");

	{
		/*
		 * Reset comes up supervisor, so drop to user mode and then try to
		 * write the status register. It must be refused.
		 */
		static const uint16_t prog[] = {
			0x2e7cu, 0x0000u, 0x8000u,	/* MOVEA.L #&8000,A7 */
			0x46fcu, 0x0000u,		/* MOVE #0,SR : leave supervisor */
			0x46fcu, 0x2700u,		/* MOVE #&2700,SR : refused */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		put_vector(CPU68000_VEC_PRIVILEGE, 0x3000);
		ram[0x3000] = 0x4e;		/* the handler: STOP #&2700 */
		ram[0x3001] = 0x72;
		ram[0x3002] = 0x27;
		ram[0x3003] = 0x00;
		step_n(2);
		check("dropping out of supervisor mode works",
		      !flag(CPU68000_SR_S));
		check_u32("and A7 became the USER stack pointer, which is zero",
		          cpu.a[7], 0);
		step_n(1);
		check("★ a user-mode write to the status register is refused",
		      cpu.pc == 0x3000u && !cpu.faulted);
		check("the handler runs in supervisor mode",
		      flag(CPU68000_SR_S));
		check_u32("on the supervisor stack, which was preserved",
		          cpu.a[7], 0x8000u - 6u);
	}

	{
		/* ★ STOP with nothing to interrupt it means finished. */
		static const uint16_t prog[] = { 0x702au, STOP_2700 };

		load(prog, sizeof(prog) / 2);
		(void) run_to_stop();
		check("STOP halts the core", cpu.halted && !cpu.faulted);
		check_u32("with D0 as the exit code", cpu.exit_code, 42);
		check_u32("and the reason recorded", cpu.halt_reason,
		          CPU68000_HALT_STOP);
	}

	{
		/*
		 * ★ AND STOP WITH AN INTERRUPT MEANS WAITING. The same
		 * instruction, and the difference is entirely in whether the guest
		 * offers one - which is why this core needs no equivalent of the
		 * 6809's faulting SYNC.
		 */
		static const uint16_t prog[] = {
			0x2e7cu, 0x0000u, 0x8000u,	/* MOVEA.L #&8000,A7 */
			0x4e72u, 0x2000u,		/* STOP #&2000 : interrupts on */
			0x7c07u,			/* MOVEQ #7,D6 */
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		put_vector(CPU68000_VEC_AUTOVECTOR + 4, 0x3000);
		ram[0x3000] = 0x4e;		/* the handler: RTE */
		ram[0x3001] = 0x73;
		step_n(2);
		check("STOP stopped it", cpu.halted);
		check_u32("running it further does nothing",
		          (uint32_t) cpu68000_step(&cpu), 0);

		check("an interrupt is taken by a stopped core",
		      cpu68000_interrupt(&cpu, 4, 0, 1) != 0);
		check("★ which starts it again", !cpu.halted && !cpu.stopped);
		(void) run_to_stop();
		check_u32("and the instruction after the STOP then runs",
		          cpu.d[6], 7);
	}

	{
		/* An interrupt below the mask is refused; level 7 never is. */
		static const uint16_t prog[] = {
			0x2e7cu, 0x0000u, 0x8000u,
			STOP_2700
		};

		load(prog, sizeof(prog) / 2);
		put_vector(CPU68000_VEC_AUTOVECTOR + 3, 0x3000);
		put_vector(CPU68000_VEC_AUTOVECTOR + 7, 0x3000);
		step_n(1);
		check("reset masks interrupts at 7, so level 3 is refused",
		      cpu68000_interrupt(&cpu, 3, 0, 1) == 0);
		check("★ but level 7 is taken whatever the mask says",
		      cpu68000_interrupt(&cpu, 7, 0, 1) != 0);
	}
}

int
main(void)
{
	printf("Motorola 68000 core\n");

	test_table();
	test_moves();
	test_arithmetic();
	test_shifts_and_bits();
	test_branches();
	test_privilege_and_stop();

	printf("\n%d failure(s)\n", failures);
	return failures == 0 ? 0 : 1;
}
