#!/usr/bin/env python3
#
# mkresfs.py - build the ResourceFS file chain the USB card's ROM carries for
# MultiFSFiler
#
# Copyright (C) 2026 Andy Timmins
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# MultiFSFiler registers this chain at initialisation, which puts its sprites
# and window template in Resources:$.Resources.MultiFS - out of the card's own
# ROM, so nothing is installed on a disc and they are present exactly when the
# card is.
#
# This is RPCEmuGfx's mkresfs.py with the application scaffolding taken out.
# What goes into Resources: is a RESOURCES directory rather than an Apps entry,
# because a filer is not an application: it has no !Run, no !Boot and no
# !RunImage, only the files its module reads for itself.
#
# Every file here whose name carries a RISC OS filetype suffix (Sprites,ff9 /
# Templates,fec and so on) is picked up automatically: drop one in and it
# appears, with no change to the assembler or the Makefile.
#
# The format is the one ResourceFS documents: per file, an offset to the next
# entry, the load and exec addresses and size as OS_File would give them, the
# attributes, the name without "$.", then (word-aligned) the size again plus
# four, then the data. A single zero word ends the list.

import os
import re
import sys

RESDIR = "Resources.MultiFS"	# where the files appear under Resources:$
ATTR = 3			# read/write, as ROM files are

TYPE_TEXT = 0xFFF
TYPE_SPRITE = 0xFF9
TYPE_TEMPLATE = 0xFEC

# Names that need no suffix: the type follows from the name.
KNOWN = {
    "Messages": TYPE_TEXT,
    "Sprites": TYPE_SPRITE,
    "Sprites22": TYPE_SPRITE,
    "Templates": TYPE_TEMPLATE,
}

# Build products that happen to carry a filetype suffix. Without this the
# module images are picked up and embedded inside themselves.
EXCLUDE = {"70-multifs,ffa", "80-multifsfiler,ffa"}

SUFFIX = re.compile(r"^(?P<name>.+),(?P<type>[0-9a-fA-F]{3})$")


def load_address(filetype):
    """The load address OS_File would report for a file of this type."""
    return 0xFFF00000 | ((filetype & 0xFFF) << 8)


def asm_label(name):
    """A label safe for the assembler, derived from a RISC OS leaf name."""
    return "rf_" + re.sub(r"[^A-Za-z0-9]", "_", name).lower()


def collect(directory):
    """Every resource file here, sorted so the build is reproducible."""
    found = []
    for entry in sorted(os.listdir(directory)):
        path = os.path.join(directory, entry)
        if not os.path.isfile(path):
            continue
        if entry in EXCLUDE:
            continue
        m = SUFFIX.match(entry)
        if m is not None:
            found.append((m.group("name"), int(m.group("type"), 16), entry))
        elif entry in KNOWN:
            found.append((entry, KNOWN[entry], entry))
    return found


def main():
    directory = sys.argv[1] if len(sys.argv) > 1 else "."
    out_path = sys.argv[2] if len(sys.argv) > 2 else "resfs.inc"

    entries = collect(directory)

    lines = [
        "@ Generated by mkresfs.py - do not edit.",
        "@",
        "@ What MultiFSFiler registers with ResourceFS, so that its sprites and",
        "@ window template are in Resources:$.%s while the card is" % RESDIR,
        "@ present and nowhere at all when it is not. Every file in",
        "@ riscos-progs/MultiFS with a filetype suffix is here automatically.",
        "",
        "\tATTR_READ\t= %d" % ATTR,
        "",
        "resfs_files:",
    ]

    labels = [asm_label(name) for name, _, _ in entries]
    labels.append("rf_end")

    for i, (name, filetype, filename) in enumerate(entries):
        label, nxt = labels[i], labels[i + 1]
        data_label = label + "_data"
        end_label = label + "_end"

        lines += [
            "",
            "%s:" % label,
            "\t.int\t%s - %s" % (nxt, label),
            "\t.int\t0x%08x\t\t@ filetype &%03X" % (load_address(filetype), filetype),
            "\t.int\t0",
            "\t.int\t%s - %s" % (end_label, data_label),
            "\t.int\tATTR_READ",
            "\t.string\t\"%s.%s\"" % (RESDIR, name),
            "\t.balign\t4, 0",
            "\t.int\t%s - %s + 4" % (end_label, data_label),
            "%s:" % data_label,
            "\t.incbin\t\"%s\"" % filename,
            "%s:" % end_label,
            "\t.balign\t4, 0",
        ]

    lines += ["", "rf_end:", "\t.int\t0\t\t\t@ end of the list", ""]

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print("resfs.inc: %s" % (", ".join(name for name, _, _ in entries) or "(nothing)"))


if __name__ == "__main__":
    main()
