/*
  RPCEmu - An Acorn system emulator

  Copyright (C) 2026 Andy Timmins

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * openbus_coproc.c - a co-processor card for the OPEN Bus, with a choice of core.
 *
 * The register map, why the core has its own RAM, why the mailbox is asymmetric
 * and what CYCLES counts are all in openbus_coproc.h.
 *
 * The three cores are reached through the small dispatch block below rather than
 * through function pointers in a vtable. There are three of them, they are chosen
 * once when the card is fitted and never change, and a switch says what is going
 * on where a table of pointers would need to be read alongside three
 * implementations of each entry.
 */

#include "openbus_coproc.h"

#include "copro_bus.h"

#include "cpu_6502.h"
#include "cpu_6800.h"
#include "cpu_6809.h"
#include "cpu_rv32i.h"
#include "cpu_z80.h"
#include "openbus.h"

#include <stdlib.h>
#include <string.h>

/*
 * How much RAM each core gets.
 *
 * The 8-bit cores get the 64K that is their whole address space, so their
 * aperture covers everything they can reach and no address they can form is
 * outside it. RV32I gets a megabyte: enough for compiled C with its data and a
 * stack, and small enough that a card is not quietly asking for real memory the
 * guest might want.
 */
#define COPROC_RAM_RV32I	(1024u * 1024u)
#define COPROC_RAM_6502		(64u * 1024u)
#define COPROC_RAM_Z80		(64u * 1024u)
#define COPROC_RAM_6809		(64u * 1024u)
#define COPROC_RAM_6800		(64u * 1024u)

/* The size asked for, in bytes; zero means the core's default. Set from the
   machine's settings before the card is fitted, as the core selection is. */
static uint32_t coproc_requested_ram_bytes;

typedef struct {
	openbus_coproc_core core;

	uint8_t *ram;
	uint32_t ram_size;

	/* One core is fitted, so the states share their space. */
	union {
		rv32i_state rv32i;
		cpu6502_state m6502;
		cpu_z80_state z80;
		cpu6809_state m6809;
		cpu6800_state m6800;
	} cpu;

	uint32_t ctrl;
	uint32_t entry;
	uint32_t addr;		/* the aperture */
	uint32_t mbox_tx;
	uint32_t mbox_rx;

	int irq;		/* is this card holding nPIRQ? */
	int stop_reported;	/* has the stop that raised it been acted on? */

	uint32_t dma_host;
	uint32_t dma_local;
	uint32_t dma_len;	/* words still to move */
	int dma_to_host;
	int dma_control;	/* the control area rather than card RAM */
	int dma_busy;

	/* The card's own memory: region table, write log and latch pages. The core
	   cannot see it, which is the point - see the note in openbus_coproc.h. */
	uint8_t *ctl;
	uint32_t ctl_size;
	uint32_t ctl_addr;	/* its aperture */

	/* What a core's accesses mean. Owns nothing; points at ram and ctl. */
	copro_bus bus;
	/* The decode's own hook, which the card's wraps. */
	cpu_mem_hook bus_hook;

	uint32_t regsel;	/* which core register REGDATA reaches */
	uint32_t runfor;	/* cycle budget for a run; zero means no limit */
	uint32_t stop_reason;
	uint32_t irqctrl;
} coproc_state;

/* One card, one slot, so the state is static rather than allocated - as the stub
   card's is. Only ram is owned, and close() frees it. */
static coproc_state cp;

/* Set from the command line, long before there is a bus to fit anything to. */
static int coproc_requested;
static openbus_coproc_core coproc_requested_core;

/* ------------------------------------------------------------ core dispatch */

/*
 * ★ ONE TABLE, NOT TWENTY-FOUR SWITCHES.
 *
 * Every one of these operations used to be its own switch on cp.core, with the
 * Z80 as the "default" case. That was survivable with three cores and became a
 * trap the moment there were more: a core that a switch had not been taught
 * about did not fail to build, it silently behaved as a Z80. Adding a core also
 * meant finding all twenty-four of them.
 *
 * So a core is a row in coproc_cores[] below. The accessors that are identical
 * in shape across every core - is it halted, what is its program counter, how
 * many cycles has it used - are generated by the macro, because writing them out
 * for seven cores would be four hundred lines of one-liners in which a mistake
 * would be invisible. The ones that genuinely differ per core, chiefly the reset
 * signature, the register numbering and how an interrupt is offered, are written
 * out.
 */

/*
 * The common accessors for one core. @tag names the functions, @member is the
 * core's slot in the union, and @pcast is what its program counter and entry
 * address have to be narrowed to - a 16-bit core cannot take a 32-bit entry.
 */
#define COPROC_CORE_ACCESSORS(tag, member, pcast, reset_fn, run_fn, step_fn, hook_fn) \
	static void tag##_reset(uint32_t entry)					\
	{ reset_fn(&cp.cpu.member, (pcast) entry); }				\
	static int tag##_run(int cycles)					\
	{ return run_fn(&cp.cpu.member, cycles); }				\
	static int tag##_step(void)						\
	{ return step_fn(&cp.cpu.member); }					\
	static int tag##_halted(void)	{ return cp.cpu.member.halted; }	\
	static int tag##_faulted(void)	{ return cp.cpu.member.faulted; }	\
	static int tag##_stalled(void)	{ return cp.cpu.member.stalled; }	\
	static void tag##_clear_stall(void) { cp.cpu.member.stalled = 0; }	\
	static uint32_t tag##_pc(void)	{ return cp.cpu.member.pc; }		\
	static uint32_t tag##_cycles(void)					\
	{ return (uint32_t) cp.cpu.member.cycles; }				\
	static uint32_t tag##_fault_cause(void)					\
	{ return cp.cpu.member.fault_cause; }					\
	static uint32_t tag##_fault_addr(void)					\
	{ return cp.cpu.member.fault_addr; }					\
	static uint32_t tag##_exit_code(void)					\
	{ return cp.cpu.member.exit_code; }					\
	static void tag##_set_hook(const cpu_mem_hook *hook)			\
	{ hook_fn(&cp.cpu.member, hook); }

COPROC_CORE_ACCESSORS(ops_rv32i, rv32i, uint32_t,
                      rv32i_reset, rv32i_run, rv32i_step, rv32i_set_mem_hook)
COPROC_CORE_ACCESSORS(ops_m6502, m6502, uint16_t,
                      cpu6502_reset, cpu6502_run, cpu6502_step, cpu6502_set_mem_hook)
COPROC_CORE_ACCESSORS(ops_z80, z80, uint16_t,
                      cpu_z80_reset, cpu_z80_run, cpu_z80_step, cpu_z80_set_mem_hook)
COPROC_CORE_ACCESSORS(ops_m6809, m6809, uint16_t,
                      cpu6809_reset, cpu6809_run, cpu6809_step,
                      cpu6809_set_mem_hook)
COPROC_CORE_ACCESSORS(ops_m6800, m6800, uint16_t,
                      cpu6800_reset, cpu6800_run, cpu6800_step,
                      cpu6800_set_mem_hook)

/*
 * The 65C02 IS the 6502 core with its CMOS flag set, so it shares every accessor
 * and its own row differs only in the name, the ID and the fact that fit() turns
 * that flag on. A second copy of the file would be seven hundred lines that have
 * to be fixed twice.
 */

/* ---- the register numbering, which is each core's own ------------------- */

static uint32_t
ops_rv32i_reg_read(uint32_t sel)
{
	if (sel < 32) {
		return cp.cpu.rv32i.x[sel];
	}
	return (sel == 32) ? cp.cpu.rv32i.pc : 0xffffffffu;
}

static void
ops_rv32i_reg_write(uint32_t sel, uint32_t val)
{
	/* x0 is hardwired to zero on a RISC-V and stays that way here: a guest
	   writing it would break every instruction that reads zero from it. */
	if (sel > 0 && sel < 32) {
		cp.cpu.rv32i.x[sel] = val;
	} else if (sel == 32) {
		cp.cpu.rv32i.pc = val;
	}
}

static uint32_t
ops_m6502_reg_read(uint32_t sel)
{
	switch (sel) {
	case 0:	return cp.cpu.m6502.a;
	case 1:	return cp.cpu.m6502.x;
	case 2:	return cp.cpu.m6502.y;
	case 3:	return cp.cpu.m6502.sp;
	case 4:	return cp.cpu.m6502.p;
	case 5:	return cp.cpu.m6502.pc;
	default: return 0xffffffffu;
	}
}

static void
ops_m6502_reg_write(uint32_t sel, uint32_t val)
{
	switch (sel) {
	case 0:	cp.cpu.m6502.a = (uint8_t) val; break;
	case 1:	cp.cpu.m6502.x = (uint8_t) val; break;
	case 2:	cp.cpu.m6502.y = (uint8_t) val; break;
	case 3:	cp.cpu.m6502.sp = (uint8_t) val; break;
	case 4:	cp.cpu.m6502.p = (uint8_t) val; break;
	case 5:	cp.cpu.m6502.pc = (uint16_t) val; break;
	default: break;
	}
}

/*
 * The 6809's own numbering. Its two accumulators come first, then the four
 * 16-bit registers in the order a programmer lists them, then the two that are
 * neither: the direct page and the condition codes. D is not here because it is
 * not a register - it is A and B side by side, and a guest that wants it can
 * read both.
 */
static uint32_t
ops_m6809_reg_read(uint32_t sel)
{
	switch (sel) {
	case 0:	return cp.cpu.m6809.a;
	case 1:	return cp.cpu.m6809.b;
	case 2:	return cp.cpu.m6809.x;
	case 3:	return cp.cpu.m6809.y;
	case 4:	return cp.cpu.m6809.u;
	case 5:	return cp.cpu.m6809.s;
	case 6:	return cp.cpu.m6809.dp;
	case 7:	return cp.cpu.m6809.cc;
	case 8:	return cp.cpu.m6809.pc;
	default: return 0xffffffffu;
	}
}

static void
ops_m6809_reg_write(uint32_t sel, uint32_t val)
{
	switch (sel) {
	case 0:	cp.cpu.m6809.a = (uint8_t) val; break;
	case 1:	cp.cpu.m6809.b = (uint8_t) val; break;
	case 2:	cp.cpu.m6809.x = (uint16_t) val; break;
	case 3:	cp.cpu.m6809.y = (uint16_t) val; break;
	case 4:	cp.cpu.m6809.u = (uint16_t) val; break;
	case 5:	cp.cpu.m6809.s = (uint16_t) val; break;
	case 6:	cp.cpu.m6809.dp = (uint8_t) val; break;
	case 7:	cp.cpu.m6809.cc = (uint8_t) val; break;
	case 8:	cp.cpu.m6809.pc = (uint16_t) val; break;
	default: break;
	}
}

/*
 * The 6800's numbering, which is the 6809's with what it does not have taken
 * out: no second stack, no Y, no direct page. Keeping the registers it shares
 * at the same numbers would mean leaving holes, and a hole a guest reads as
 * all-ones is worse than a shorter list.
 */
static uint32_t
ops_m6800_reg_read(uint32_t sel)
{
	switch (sel) {
	case 0:	return cp.cpu.m6800.a;
	case 1:	return cp.cpu.m6800.b;
	case 2:	return cp.cpu.m6800.x;
	case 3:	return cp.cpu.m6800.sp;
	case 4:	return cp.cpu.m6800.cc;
	case 5:	return cp.cpu.m6800.pc;
	default: return 0xffffffffu;
	}
}

static void
ops_m6800_reg_write(uint32_t sel, uint32_t val)
{
	switch (sel) {
	case 0:	cp.cpu.m6800.a = (uint8_t) val; break;
	case 1:	cp.cpu.m6800.b = (uint8_t) val; break;
	case 2:	cp.cpu.m6800.x = (uint16_t) val; break;
	case 3:	cp.cpu.m6800.sp = (uint16_t) val; break;
	case 4:	cp.cpu.m6800.cc = (uint8_t) val; break;
	case 5:	cp.cpu.m6800.pc = (uint16_t) val; break;
	default: break;
	}
}

static uint32_t
ops_z80_reg_read(uint32_t sel)
{
	switch (sel) {
	case 0:	return cp.cpu.z80.a;
	case 1:	return cp.cpu.z80.f;
	case 2:	return cp.cpu.z80.b;
	case 3:	return cp.cpu.z80.c;
	case 4:	return cp.cpu.z80.d;
	case 5:	return cp.cpu.z80.e;
	case 6:	return cp.cpu.z80.h;
	case 7:	return cp.cpu.z80.l;
	case 8:	return cp.cpu.z80.ix;
	case 9:	return cp.cpu.z80.iy;
	case 10: return cp.cpu.z80.sp;
	case 11: return cp.cpu.z80.pc;
	case 12: return cp.cpu.z80.i;
	case 13: return cp.cpu.z80.im;
	case 14: return cp.cpu.z80.iff1;
	default: return 0xffffffffu;
	}
}

static void
ops_z80_reg_write(uint32_t sel, uint32_t val)
{
	switch (sel) {
	case 0:	cp.cpu.z80.a = (uint8_t) val; break;
	case 1:	cp.cpu.z80.f = (uint8_t) val; break;
	case 2:	cp.cpu.z80.b = (uint8_t) val; break;
	case 3:	cp.cpu.z80.c = (uint8_t) val; break;
	case 4:	cp.cpu.z80.d = (uint8_t) val; break;
	case 5:	cp.cpu.z80.e = (uint8_t) val; break;
	case 6:	cp.cpu.z80.h = (uint8_t) val; break;
	case 7:	cp.cpu.z80.l = (uint8_t) val; break;
	case 8:	cp.cpu.z80.ix = (uint16_t) val; break;
	case 9:	cp.cpu.z80.iy = (uint16_t) val; break;
	case 10: cp.cpu.z80.sp = (uint16_t) val; break;
	case 11: cp.cpu.z80.pc = (uint16_t) val; break;
	case 12: cp.cpu.z80.i = (uint8_t) val; break;
	case 13: cp.cpu.z80.im = (uint8_t) (val & 3u); break;
	case 14: cp.cpu.z80.iff1 = (uint8_t) (val != 0); break;
	default: break;
	}
}

/* ---- interrupts, which every core offers differently -------------------- */

static void
ops_rv32i_interrupt(uint32_t ctrl)
{
	/* Neither: this core implements no CSRs, so it has no way to accept an
	   interrupt. Saying so plainly beats a register that silently does
	   nothing. */
	(void) ctrl;
}

static void
ops_m6502_interrupt(uint32_t ctrl)
{
	if ((ctrl & OPENBUS_COPROC_IRQ_NMI) != 0) {
		cpu6502_nmi(&cp.cpu.m6502);
	} else if ((ctrl & OPENBUS_COPROC_IRQ_ASSERT) != 0) {
		(void) cpu6502_irq(&cp.cpu.m6502);
	}
}

static void
ops_z80_interrupt(uint32_t ctrl)
{
	if ((ctrl & OPENBUS_COPROC_IRQ_NMI) != 0) {
		cpu_z80_nmi(&cp.cpu.z80);
	} else if ((ctrl & OPENBUS_COPROC_IRQ_ASSERT) != 0) {
		(void) cpu_z80_interrupt(&cp.cpu.z80,
		    (uint8_t) OPENBUS_COPROC_IRQ_VECTOR(ctrl));
	}
}

/*
 * ★ The 6809 is the one core here with TWO maskable interrupt lines, so the
 * level field is not decoration for it. IRQ and FIRQ differ in how much state
 * they push, which means a handler written for one cannot serve the other, and a
 * guest that asked for the wrong one would return from it to a wrong address.
 */
static void
ops_m6809_interrupt(uint32_t ctrl)
{
	if ((ctrl & OPENBUS_COPROC_IRQ_NMI) != 0) {
		cpu6809_nmi(&cp.cpu.m6809);
	} else if ((ctrl & OPENBUS_COPROC_IRQ_ASSERT) != 0) {
		if (OPENBUS_COPROC_IRQ_LEVEL(ctrl) == 1) {
			(void) cpu6809_firq(&cp.cpu.m6809);
		} else {
			(void) cpu6809_irq(&cp.cpu.m6809);
		}
	}
}

/* The 6800 has one maskable line, so the level field means nothing to it. */
static void
ops_m6800_interrupt(uint32_t ctrl)
{
	if ((ctrl & OPENBUS_COPROC_IRQ_NMI) != 0) {
		cpu6800_nmi(&cp.cpu.m6800);
	} else if ((ctrl & OPENBUS_COPROC_IRQ_ASSERT) != 0) {
		(void) cpu6800_irq(&cp.cpu.m6800);
	}
}

/* ---- and the table itself ----------------------------------------------- */

typedef struct {
	const char *option;	/**< what --openbus-card and the config accept */
	const char *card_name;	/**< the name the log and the inspector show */
	uint32_t id;		/**< the CORE register's value */
	uint32_t ram_default;	/**< bytes, when nothing is chosen */
	uint32_t ram_max;	/**< the most that may be FITTED */
	uint32_t ram_flat;	/**< the most it can address without paging */

	void (*reset)(uint32_t entry);
	int (*run)(int cycles);
	int (*step)(void);
	int (*halted)(void);
	int (*faulted)(void);
	int (*stalled)(void);
	void (*clear_stall)(void);
	uint32_t (*pc)(void);
	uint32_t (*cycles)(void);
	uint32_t (*fault_cause)(void);
	uint32_t (*fault_addr)(void);
	uint32_t (*exit_code)(void);
	void (*set_hook)(const cpu_mem_hook *hook);
	uint32_t (*reg_read)(uint32_t sel);
	void (*reg_write)(uint32_t sel, uint32_t val);
	void (*interrupt)(uint32_t ctrl);
} coproc_core_ops;

#define COPROC_CORE_ROW(tag)						\
	tag##_reset, tag##_run, tag##_step, tag##_halted, tag##_faulted,	\
	tag##_stalled, tag##_clear_stall, tag##_pc, tag##_cycles,	\
	tag##_fault_cause, tag##_fault_addr, tag##_exit_code,		\
	tag##_set_hook, tag##_reg_read, tag##_reg_write, tag##_interrupt

static const coproc_core_ops coproc_cores[] = {
	{ "rv32i", "OPEN Bus co-processor card (RV32IM)",
	  OPENBUS_COPROC_CORE_RV32I_ID,
	  COPROC_RAM_RV32I, OPENBUS_COPROC_RAM_MAX_RV32I,
	  OPENBUS_COPROC_RAM_MAX_RV32I,
	  COPROC_CORE_ROW(ops_rv32i) },

	{ "6502", "OPEN Bus co-processor card (6502)",
	  OPENBUS_COPROC_CORE_6502_ID,
	  COPROC_RAM_6502, OPENBUS_COPROC_RAM_MAX_8BIT, 64u * 1024u,
	  COPROC_CORE_ROW(ops_m6502) },

	{ "z80", "OPEN Bus co-processor card (Z80)",
	  OPENBUS_COPROC_CORE_Z80_ID,
	  COPROC_RAM_Z80, OPENBUS_COPROC_RAM_MAX_8BIT, 64u * 1024u,
	  COPROC_CORE_ROW(ops_z80) },

	{ "65c02", "OPEN Bus co-processor card (65C02)",
	  OPENBUS_COPROC_CORE_65C02_ID,
	  COPROC_RAM_6502, OPENBUS_COPROC_RAM_MAX_8BIT, 64u * 1024u,
	  COPROC_CORE_ROW(ops_m6502) },

	/* The 8080 is the Z80 core with its own flag semantics and the Z80's own
	   instructions withdrawn; see cpu_z80.h. */
	{ "8080", "OPEN Bus co-processor card (8080)",
	  OPENBUS_COPROC_CORE_8080_ID,
	  COPROC_RAM_Z80, OPENBUS_COPROC_RAM_MAX_8BIT, 64u * 1024u,
	  COPROC_CORE_ROW(ops_z80) },

	{ "6809", "OPEN Bus co-processor card (6809)",
	  OPENBUS_COPROC_CORE_6809_ID,
	  COPROC_RAM_6809, OPENBUS_COPROC_RAM_MAX_8BIT, 64u * 1024u,
	  COPROC_CORE_ROW(ops_m6809) },

	/* Offered once, not three times: the 6802 and the 6808 are this same
	   instruction set. See cpu_6800.h. */
	{ "6800", "OPEN Bus co-processor card (6800)",
	  OPENBUS_COPROC_CORE_6800_ID,
	  COPROC_RAM_6800, OPENBUS_COPROC_RAM_MAX_8BIT, 64u * 1024u,
	  COPROC_CORE_ROW(ops_m6800) },
};

#define COPROC_CORE_COUNT ((int) (sizeof(coproc_cores) / sizeof(coproc_cores[0])))

/* The row for the fitted core, or the first one if nothing sensible is set: a
   NULL here would be a crash rather than a wrong answer, and neither is wanted
   in a register read. */
static const coproc_core_ops *
core_ops(void)
{
	if ((int) cp.core < 0 || (int) cp.core >= COPROC_CORE_COUNT) {
		return &coproc_cores[0];
	}
	return &coproc_cores[cp.core];
}

/*
 * Hand the fitted core whatever IRQCTRL is asking for. Level-triggered as the
 * hardware is for the maskable line: while the bit is set the interrupt is
 * offered, and the guest clears it when its device would stop asserting.
 */
static void
coproc_apply_interrupts(void)
{
	const uint32_t ctrl = cp.irqctrl;

	core_ops()->interrupt(ctrl);

	/* The non-maskable one is edge triggered on the way in, or it would be
	   taken again on every register write. */
	if ((ctrl & OPENBUS_COPROC_IRQ_NMI) != 0) {
		cp.irqctrl &= ~(uint32_t) OPENBUS_COPROC_IRQ_NMI;
	}
}

static void core_reset(void)		{ core_ops()->reset(cp.entry); }
static int core_run(int cycles)		{ return core_ops()->run(cycles); }
static int core_step(void)		{ return core_ops()->step(); }
static int core_halted(void)		{ return core_ops()->halted(); }
static int core_faulted(void)		{ return core_ops()->faulted(); }
static int core_stalled(void)		{ return core_ops()->stalled(); }
static void core_clear_stall(void)	{ core_ops()->clear_stall(); }
static uint32_t core_pc(void)		{ return core_ops()->pc(); }
static uint32_t core_cycles(void)	{ return core_ops()->cycles(); }
static uint32_t core_fault_cause(void)	{ return core_ops()->fault_cause(); }
static uint32_t core_fault_addr(void)	{ return core_ops()->fault_addr(); }
static uint32_t core_exit_code(void)	{ return core_ops()->exit_code(); }
static uint32_t core_id(void)		{ return core_ops()->id; }
static uint32_t core_reg_read(uint32_t sel)	{ return core_ops()->reg_read(sel); }
static void core_reg_write(uint32_t sel, uint32_t val)
{ core_ops()->reg_write(sel, val); }

/* ------------------------------------------------- the Z80's port space */

/*
 * Port 0 is the mailbox; every other port is the latch inside the core, so a
 * program that only talks to itself still gets 255 working ports. See the
 * asymmetry note in openbus_coproc.h for why only the Z80 has this.
 */

static uint8_t
coproc_io_in(void *ctx, uint8_t port)
{
	(void) ctx;

	if (port == 0) {
		return (uint8_t) cp.mbox_tx;
	}
	return cp.cpu.z80.ports[port];
}

static void
coproc_io_out(void *ctx, uint8_t port, uint8_t val)
{
	(void) ctx;

	cp.cpu.z80.ports[port] = val;
	if (port == 0) {
		cp.mbox_rx = val;
	}
}

/* ------------------------------------------------------------- the aperture */

/**
 * Read @size bytes of card RAM at the aperture, advancing it.
 *
 * The advance is a side effect of a read, which is normally a thing to avoid -
 * but it is what makes the aperture worth having, and it is safe here for a
 * reason worth writing down: mem_phys_read8_debug() handles only ROM, VRAM and
 * RAM, so the debugger and the inspector cannot reach this window at all. There
 * is no way for a passive observer to disturb the aperture. See openbus.h.
 */
static uint32_t
aperture_read(openbus_size size)
{
	uint32_t val = 0;
	unsigned i;

	if (cp.ram == NULL || cp.ram_size == 0) {
		return 0xffffffffu;
	}

	for (i = 0; i < (unsigned) size; i++) {
		/* Wraps at the end of card RAM rather than faulting: the aperture
		   is a window a guest walks, and stopping dead at the top would
		   need an error path in every caller for no benefit. */
		val |= (uint32_t) cp.ram[(cp.addr + i) % cp.ram_size] << (i * 8);
	}
	cp.addr = (cp.addr + (uint32_t) size) % cp.ram_size;
	return val;
}

static void
aperture_write(openbus_size size, uint32_t val)
{
	unsigned i;

	if (cp.ram == NULL || cp.ram_size == 0) {
		return;
	}

	for (i = 0; i < (unsigned) size; i++) {
		cp.ram[(cp.addr + i) % cp.ram_size] = (uint8_t) (val >> (i * 8));
	}
	cp.addr = (cp.addr + (uint32_t) size) % cp.ram_size;
}

/*
 * The control area's aperture. The same shape as the card RAM one above and for
 * the same reason: a guest walks it with ordinary writes and needs no physical
 * address to do it.
 */
static uint32_t
ctl_aperture_read(openbus_size size)
{
	uint32_t val = 0;
	unsigned i;

	if (cp.ctl == NULL || cp.ctl_size == 0) {
		return 0xffffffffu;
	}

	for (i = 0; i < (unsigned) size; i++) {
		val |= (uint32_t) cp.ctl[(cp.ctl_addr + i) % cp.ctl_size] << (i * 8);
	}
	cp.ctl_addr = (cp.ctl_addr + (uint32_t) size) % cp.ctl_size;
	return val;
}

static void
ctl_aperture_write(openbus_size size, uint32_t val)
{
	unsigned i;

	if (cp.ctl == NULL || cp.ctl_size == 0) {
		return;
	}

	for (i = 0; i < (unsigned) size; i++) {
		cp.ctl[(cp.ctl_addr + i) % cp.ctl_size] = (uint8_t) (val >> (i * 8));
	}
	cp.ctl_addr = (cp.ctl_addr + (uint32_t) size) % cp.ctl_size;
}

/*
 * Hand the fitted core a hook onto the decode, or take it away again.
 *
 * Called whenever the map changes, because whether any region can stall decides
 * whether the core saves its registers before each instruction, and that is a
 * per-instruction cost nobody should pay for a map that cannot stall.
 */
/*
 * The card's own hook, wrapped round the decode's.
 *
 * ★ WHY IT IS NOT JUST THE DECODE'S HOOK. The Z80's port 0 is this card's
 * mailbox and its other ports are a latch inside the core, and both predate the
 * address map. Installing the decode's hook directly took them away, which broke
 * the mailbox the moment the map was introduced - caught by the card's own test
 * rather than by anything in the new code.
 *
 * So a port that no region describes still behaves as it always did, and a region
 * wins where one exists: a machine being emulated says what its ports are, and
 * anything it has not claimed is the card's.
 */
static cpu_mem_result
coproc_hook_read(void *ctx, uint32_t addr, uint8_t *value)
{
	const int is_port = (addr & CPU_MEM_PORT) != 0;
	const uint32_t bare = addr & ~CPU_MEM_PORT;

	if (is_port && copro_bus_region(&cp.bus, bare, 1) == NULL) {
		*value = coproc_io_in(ctx, (uint8_t) bare);
		return CPU_MEM_OK;
	}
	return cp.bus_hook.read(cp.bus_hook.ctx, addr, value);
}

static cpu_mem_result
coproc_hook_write(void *ctx, uint32_t addr, uint8_t value)
{
	const int is_port = (addr & CPU_MEM_PORT) != 0;
	const uint32_t bare = addr & ~CPU_MEM_PORT;

	if (is_port && copro_bus_region(&cp.bus, bare, 1) == NULL) {
		coproc_io_out(ctx, (uint8_t) bare, value);
		return CPU_MEM_OK;
	}
	return cp.bus_hook.write(cp.bus_hook.ctx, addr, value);
}

static void
coproc_rehook(void)
{
	cpu_mem_hook hook;

	copro_bus_hook(&cp.bus, &cp.bus_hook);
	hook.ctx = NULL;
	hook.read = coproc_hook_read;
	hook.write = coproc_hook_write;
	hook.can_stall = cp.bus_hook.can_stall;

	core_ops()->set_hook(&hook);
}

/* ------------------------------------------------------------------ the card */

static void
coproc_drop_irq(void)
{
	if (cp.irq) {
		cp.irq = 0;
		openbus_master_set_irq(0);
	}
}

static void
coproc_reset(void *p)
{
	(void) p;

	coproc_drop_irq();

	cp.ctrl = 0;
	cp.addr = 0;
	cp.mbox_tx = 0;
	cp.mbox_rx = 0;
	cp.stop_reported = 0;
	cp.dma_host = 0;
	cp.dma_local = 0;
	cp.dma_len = 0;
	cp.dma_to_host = 0;
	cp.dma_busy = 0;

	/* ENTRY survives, because a machine reset should not lose where the guest
	   said the program starts; the core is put back to that entry point. */
	core_reset();
}

static uint32_t
coproc_status(void)
{
	uint32_t val = 0;

	if ((cp.ctrl & OPENBUS_COPROC_CTRL_RUN) && !core_halted() && !core_faulted()) {
		val |= OPENBUS_COPROC_STATUS_RUNNING;
	}
	if (core_halted()) {
		val |= OPENBUS_COPROC_STATUS_HALTED;
	}
	if (core_faulted()) {
		val |= OPENBUS_COPROC_STATUS_FAULT;
	}
	if (cp.irq) {
		val |= OPENBUS_COPROC_STATUS_IRQ;
	}
	if (cp.dma_busy) {
		val |= OPENBUS_COPROC_STATUS_DMA;
	}
	if (core_stalled()) {
		/* Neither a fault nor a halt: the core is part way through an
		   instruction that the guest has to answer for. */
		val |= OPENBUS_COPROC_STATUS_WAITING;
	}
	return val;
}

/** Every register except DATA, which has its own path because it moves memory. */
static uint32_t
coproc_read_word(uint32_t reg)
{
	switch (reg) {
	case OPENBUS_COPROC_REG_ID:		return OPENBUS_COPROC_ID;
	case OPENBUS_COPROC_REG_CORE:		return core_id();
	case OPENBUS_COPROC_REG_RAMSIZE:	return cp.ram_size;
	case OPENBUS_COPROC_REG_CTRL:		return cp.ctrl;
	case OPENBUS_COPROC_REG_STATUS:		return coproc_status();
	case OPENBUS_COPROC_REG_ENTRY:		return cp.entry;
	case OPENBUS_COPROC_REG_ADDR:		return cp.addr;
	case OPENBUS_COPROC_REG_MBOX_TX:	return cp.mbox_tx;
	case OPENBUS_COPROC_REG_MBOX_RX:	return cp.mbox_rx;
	case OPENBUS_COPROC_REG_CYCLES:		return core_cycles();
	case OPENBUS_COPROC_REG_PC:		return core_pc();
	case OPENBUS_COPROC_REG_FAULT:
		/* Zero unless there is a fault, so that a guest reading FAULT
		   without checking STATUS first is not misled by the cause of an
		   older one. */
		return core_faulted() ? core_fault_cause() : 0;
	case OPENBUS_COPROC_REG_FAULTADDR:
		return core_faulted() ? core_fault_addr() : 0;
	case OPENBUS_COPROC_REG_DMAHOST:	return cp.dma_host;
	case OPENBUS_COPROC_REG_DMALOCAL:	return cp.dma_local;
	case OPENBUS_COPROC_REG_DMALEN:		return cp.dma_len;
	case OPENBUS_COPROC_REG_DMACTRL:
		return (uint32_t) ((cp.dma_busy ? OPENBUS_COPROC_DMA_START : 0) |
		                   (cp.dma_to_host ? OPENBUS_COPROC_DMA_TO_HOST : 0) |
		                   (cp.dma_control ? OPENBUS_COPROC_DMA_CONTROL : 0));
	case OPENBUS_COPROC_REG_RUNFOR:		return cp.runfor;
	case OPENBUS_COPROC_REG_STOPREASON:	return cp.stop_reason;
	case OPENBUS_COPROC_REG_IRQCTRL:	return cp.irqctrl;
	case OPENBUS_COPROC_REG_MAPOFF:		return cp.bus.map_off;
	case OPENBUS_COPROC_REG_MAPCOUNT:	return cp.bus.map_count;
	case OPENBUS_COPROC_REG_LOGOFF:		return cp.bus.log_off;
	case OPENBUS_COPROC_REG_LOGENTRIES:	return cp.bus.log_entries;
	case OPENBUS_COPROC_REG_LOGHEAD:	return cp.bus.log_head;
	case OPENBUS_COPROC_REG_LOGTAIL:	return cp.bus.log_tail;
	case OPENBUS_COPROC_REG_WAITADDR:	return cp.bus.wait_addr;
	case OPENBUS_COPROC_REG_WAITDATA:	return cp.bus.wait_value;
	case OPENBUS_COPROC_REG_WAITINFO:
		return (cp.bus.wait_is_write ? 1u : 0u) |
		       (cp.bus.wait_is_port ? 2u : 0u);
	case OPENBUS_COPROC_REG_CTLADDR:	return cp.ctl_addr;
	case OPENBUS_COPROC_REG_CTLSIZE:	return cp.ctl_size;
	case OPENBUS_COPROC_REG_REGSEL:		return cp.regsel;
	case OPENBUS_COPROC_REG_REGDATA:	return core_reg_read(cp.regsel);
	default:
		/* Nothing driving this address, including IRQCLEAR: it is write
		   only, and reading it would suggest otherwise. */
		return 0xffffffffu;
	}
}

/**
 * Note the core having stopped, once.
 *
 * Raising nPIRQ is what saves the guest from polling. It happens once per stop,
 * not once per timeslice, or the line would be re-asserted immediately after the
 * guest cleared it and the machine would spend its life in an interrupt handler.
 */
static void
coproc_note_stop(void)
{
	if (cp.stop_reported) {
		return;
	}
	if (!core_halted() && !core_faulted()) {
		return;
	}

	cp.stop_reported = 1;

	if (core_halted()) {
		cp.mbox_rx = core_exit_code();
	}

	/* RUN is cleared so that STATUS stops claiming the core is running and a
	   later timeslice does not try to execute a halted core. */
	cp.ctrl &= ~(uint32_t) OPENBUS_COPROC_CTRL_RUN;

	if (cp.ctrl & OPENBUS_COPROC_CTRL_IRQ_ON_HALT) {
		cp.irq = 1;
		openbus_master_set_irq(1);
	}
}

static void
coproc_start_dma(void)
{
	/* A transfer that would run outside card RAM does not start, and DMALEN
	   keeps its value so the guest can see that nothing happened. Clamping
	   instead would move somebody's data by an amount they did not ask for. */
	if (cp.ram == NULL || cp.dma_len == 0) {
		return;
	}
	if ((cp.dma_local & 3u) != 0) {
		return;		/* words, so the local address must be aligned */
	}
	/* The bound is checked before the subtraction that uses it, or an address
	   past the end of RAM would underflow and look like room to spare. */
	if (cp.dma_local >= cp.ram_size) {
		return;
	}
	if (cp.dma_len > (cp.ram_size - cp.dma_local) / 4u) {
		return;
	}

	cp.dma_busy = 1;
}

/**
 * Move the DMA on, as a bus master.
 *
 * @return cycles used, which the caller charges against the host's budget - so a
 *         transfer costs the guest real time rather than being free, exactly as
 *         the stub card's copy does.
 */
static int
coproc_run_dma(int budget)
{
	int used = 0;

	while (used < budget && cp.dma_len > 0) {
		int words = OPENBUS_COPROC_DMA_WORDS_PER_CYCLE;

		while (words-- > 0 && cp.dma_len > 0) {
			if (cp.dma_to_host) {
				const uint32_t word =
				    (uint32_t) cp.ram[cp.dma_local] |
				    ((uint32_t) cp.ram[cp.dma_local + 1] << 8) |
				    ((uint32_t) cp.ram[cp.dma_local + 2] << 16) |
				    ((uint32_t) cp.ram[cp.dma_local + 3] << 24);

				openbus_master_write32(cp.dma_host, word);
			} else {
				const uint32_t word = openbus_master_read32(cp.dma_host);

				cp.ram[cp.dma_local] = (uint8_t) word;
				cp.ram[cp.dma_local + 1] = (uint8_t) (word >> 8);
				cp.ram[cp.dma_local + 2] = (uint8_t) (word >> 16);
				cp.ram[cp.dma_local + 3] = (uint8_t) (word >> 24);
			}
			cp.dma_host += 4;
			cp.dma_local += 4;
			cp.dma_len--;
		}
		used++;
	}

	if (cp.dma_len == 0) {
		cp.dma_busy = 0;
	}
	return used;
}

static uint32_t
coproc_reg_read(void *p, uint32_t offset, openbus_size size)
{
	const uint32_t reg = offset & ~3u;
	const unsigned shift = (offset & 3u) * 8u;
	uint32_t word;

	(void) p;

	if (reg == OPENBUS_COPROC_REG_DATA) {
		return aperture_read(size);
	}
	if (reg == OPENBUS_COPROC_REG_CTLDATA) {
		return ctl_aperture_read(size);
	}

	word = coproc_read_word(reg);

	if (size == OPENBUS_SIZE_32) {
		return word;
	}

	/* A narrow access sees the addressed part of the word, little-endian, as
	   it would on the bus. The stub card answers the whole word whatever the
	   width; doing it properly here costs two lines and means a guest reading
	   the second byte of a register gets the second byte. */
	word >>= shift;
	return (size == OPENBUS_SIZE_8) ? (word & 0xffu) : (word & 0xffffu);
}

static void
coproc_reg_write(void *p, uint32_t offset, openbus_size size, uint32_t val)
{
	const uint32_t reg = offset & ~3u;

	(void) p;

	if (reg == OPENBUS_COPROC_REG_DATA) {
		aperture_write(size, val);
		return;
	}
	if (reg == OPENBUS_COPROC_REG_CTLDATA) {
		ctl_aperture_write(size, val);
		return;
	}
	(void) size;

	/*
	 * Narrow writes to the control registers are not merged into the word
	 * they address: every register here is a word, a guest driving this card
	 * writes words, and a byte write that quietly changed one quarter of
	 * CTRL would be a harder thing to explain than one that plainly writes
	 * the value given. The aperture above is the exception because its width
	 * is the point of it.
	 */

	switch (reg) {
	case OPENBUS_COPROC_REG_CTRL:
		/* RESET first and on its own: a write asking to reset and to run
		   in one go is a contradiction, and honouring the reset is the
		   less surprising reading. Self-clearing, so the bit never
		   sticks. */
		if (val & OPENBUS_COPROC_CTRL_RESET) {
			coproc_reset(NULL);
			return;
		}

		cp.ctrl = val & (OPENBUS_COPROC_CTRL_RUN |
		                 OPENBUS_COPROC_CTRL_IRQ_ON_HALT);

		/* Starting a core that has stopped arms the report again, so the
		   next halt raises nPIRQ as the first one did. */
		if ((cp.ctrl & OPENBUS_COPROC_CTRL_RUN) && !core_halted() &&
		    !core_faulted()) {
			cp.stop_reported = 0;
		}

		if (val & OPENBUS_COPROC_CTRL_STEP) {
			/* Executed here rather than on the next timeslice: a guest
			   that writes STEP and then reads PC expects the step to
			   have happened, and this write is already running on the
			   thread that owns the machine. */
			(void) core_step();
			coproc_note_stop();
		}
		break;

	case OPENBUS_COPROC_REG_ENTRY:
		cp.entry = val;
		break;

	case OPENBUS_COPROC_REG_RUNFOR:
		cp.runfor = val;
		break;

	case OPENBUS_COPROC_REG_IRQCTRL:
		cp.irqctrl = val;
		coproc_apply_interrupts();
		break;

	case OPENBUS_COPROC_REG_MAPOFF:
		/* Taken together with MAPCOUNT: an offset on its own describes
		   nothing, so the map is only re-pointed when the count is set. */
		cp.bus.map_off = val;
		break;

	case OPENBUS_COPROC_REG_MAPCOUNT:
		if (copro_bus_set_map(&cp.bus, cp.bus.map_off, val) == 0) {
			/* Refused, because it would not fit: the map in use is left
			   alone rather than half-applied. */
			break;
		}
		coproc_rehook();
		break;

	case OPENBUS_COPROC_REG_LOGOFF:
		cp.bus.log_off = val;
		break;

	case OPENBUS_COPROC_REG_LOGENTRIES:
		(void) copro_bus_set_log(&cp.bus, cp.bus.log_off, val);
		break;

	case OPENBUS_COPROC_REG_LOGTAIL:
		/* The guest says how far it has read. Anything past the head would
		   make the ring look full of entries that were never written. */
		if (cp.bus.log_entries != 0 && val < cp.bus.log_entries) {
			cp.bus.log_tail = val;
		}
		break;

	case OPENBUS_COPROC_REG_WAITDATA:
		cp.bus.wait_value = val;
		break;

	case OPENBUS_COPROC_REG_WAITACK:
		/* Answer the waiting access and let the core continue. The value
		   for a read is whatever was written to WAITDATA. */
		if (cp.bus.stalled) {
			(void) copro_bus_resume(&cp.bus, (uint8_t) cp.bus.wait_value);
			core_clear_stall();
		}
		break;

	case OPENBUS_COPROC_REG_CTLADDR:
		cp.ctl_addr = (cp.ctl_size != 0) ? (val % cp.ctl_size) : 0;
		break;

	case OPENBUS_COPROC_REG_REGSEL:
		cp.regsel = val;
		break;

	case OPENBUS_COPROC_REG_REGDATA:
		core_reg_write(cp.regsel, val);
		break;

	case OPENBUS_COPROC_REG_ADDR:
		cp.addr = (cp.ram_size != 0) ? (val % cp.ram_size) : 0;
		break;

	case OPENBUS_COPROC_REG_MBOX_TX:
		cp.mbox_tx = val;
		break;

	case OPENBUS_COPROC_REG_IRQCLEAR:
		coproc_drop_irq();
		break;

	case OPENBUS_COPROC_REG_DMAHOST:
		cp.dma_host = val;
		break;

	case OPENBUS_COPROC_REG_DMALOCAL:
		cp.dma_local = val;
		break;

	case OPENBUS_COPROC_REG_DMALEN:
		cp.dma_len = val;
		break;

	case OPENBUS_COPROC_REG_DMACTRL:
		cp.dma_to_host = (val & OPENBUS_COPROC_DMA_TO_HOST) != 0;
		if (val & OPENBUS_COPROC_DMA_START) {
			coproc_start_dma();
		}
		break;

	default:
		/* Read-only or unimplemented. Dropped, as an undriven write is. */
		break;
	}
}

static int
coproc_run(void *p, int cycles)
{
	int used = 0;

	(void) p;

	if (cycles <= 0) {
		return 0;
	}

	/* The transfer goes first: a program waiting for its data cannot make
	   progress until the data is there, and the card is one bus master
	   whichever of the two is using it. */
	if (cp.dma_busy) {
		used += coproc_run_dma(cycles);
	}

	if ((cp.ctrl & OPENBUS_COPROC_CTRL_RUN) && used < cycles) {
		int budget = cycles - used;
		int ran;

		/*
		 * RUNFOR is what lets a guest emulate a machine a frame at a time:
		 * ask for 69888 cycles and a Spectrum frame is what comes back,
		 * however many timeslices the card is given to do it in. Zero means
		 * no limit, which is what the card did before this existed.
		 */
		if (cp.runfor != 0 && (uint32_t) budget > cp.runfor) {
			budget = (int) cp.runfor;
		}

		ran = core_run(budget);
		used += ran;

		if (cp.runfor != 0) {
			/*
			 * Floored, not subtracted: an instruction is indivisible, so
			 * a core asked for the last 2 cycles of a budget may take 4
			 * and overshoot. Subtracting would wrap the count and the
			 * budget would never reach zero - the core then ran until it
			 * halted, which is exactly what the register exists to
			 * prevent, and the test caught it.
			 */
			cp.runfor = ((uint32_t) ran >= cp.runfor)
			    ? 0 : cp.runfor - (uint32_t) ran;
			if (cp.runfor == 0) {
				/* Budget spent: stop, and leave it to the guest to
				   give another. RUN is cleared so a later timeslice
				   does not carry on past the frame it asked for. */
				cp.ctrl &= ~(uint32_t) OPENBUS_COPROC_CTRL_RUN;
				cp.stop_reason = OPENBUS_COPROC_STOP_BUDGET;
			}
		}

		if (core_faulted()) {
			cp.stop_reason = OPENBUS_COPROC_STOP_FAULT;
		} else if (core_halted()) {
			cp.stop_reason = OPENBUS_COPROC_STOP_HALTED;
		} else if (core_stalled()) {
			/* RUN stays set: answering the access is all that is needed
			   for the core to carry on where it was. */
			cp.stop_reason = OPENBUS_COPROC_STOP_WAITING;
		}

		coproc_note_stop();
	} else if ((cp.ctrl & OPENBUS_COPROC_CTRL_RUN) == 0 &&
	           cp.stop_reason == OPENBUS_COPROC_STOP_NONE) {
		cp.stop_reason = OPENBUS_COPROC_STOP_STOPPED;
	}

	return used;
}

static void
coproc_close(void *p)
{
	(void) p;

	free(cp.ram);
	cp.ram = NULL;
	cp.ram_size = 0;
	free(cp.ctl);
	cp.ctl = NULL;
	cp.ctl_size = 0;
}

/* --------------------------------------------------------------- interface */

const char *
openbus_coproc_core_name(openbus_coproc_core core)
{
	if ((int) core < 0 || (int) core >= COPROC_CORE_COUNT) {
		return NULL;
	}
	return coproc_cores[core].option;
}

int
openbus_coproc_request(const char *name)
{
	int core;

	if (name == NULL) {
		return -1;
	}

	for (core = 0; core < COPROC_CORE_COUNT; core++) {
		const char *candidate =
		    openbus_coproc_core_name((openbus_coproc_core) core);
		size_t i;

		/* Compared without regard to case, and without strcasecmp, which
		   is neither C99 nor available everywhere this builds. */
		for (i = 0; ; i++) {
			const char a = name[i];
			char b = candidate[i];

			if (a >= 'A' && a <= 'Z') {
				/* Only the name needs folding: the candidates are
				   written in lower case above. */
				if ((char) (a + ('a' - 'A')) != b) {
					break;
				}
			} else if (a != b) {
				break;
			}
			if (a == '\0') {
				coproc_requested = 1;
				coproc_requested_core = (openbus_coproc_core) core;
				return 0;
			}
		}
	}

	return -1;
}

int
openbus_coproc_requested(void)
{
	return coproc_requested;
}

openbus_coproc_core
openbus_coproc_requested_core(void)
{
	return coproc_requested_core;
}

uint32_t
openbus_coproc_ram_default(openbus_coproc_core core)
{
	if ((int) core < 0 || (int) core >= COPROC_CORE_COUNT) {
		return 0;
	}
	return coproc_cores[core].ram_default;
}

uint32_t
openbus_coproc_ram_max(openbus_coproc_core core)
{
	if ((int) core < 0 || (int) core >= COPROC_CORE_COUNT) {
		return 0;
	}
	return coproc_cores[core].ram_max;
}

uint32_t
openbus_coproc_ram_flat_limit(openbus_coproc_core core)
{
	if ((int) core < 0 || (int) core >= COPROC_CORE_COUNT) {
		return 0;
	}
	return coproc_cores[core].ram_flat;
}

uint32_t
openbus_coproc_request_ram(uint32_t bytes)
{
	coproc_requested_ram_bytes = bytes;
	return openbus_coproc_requested_ram();
}

uint32_t
openbus_coproc_requested_ram(void)
{
	const uint32_t max = openbus_coproc_ram_max(coproc_requested_core);
	const uint32_t def = openbus_coproc_ram_default(coproc_requested_core);

	if (coproc_requested_ram_bytes == 0) {
		return def;
	}
	if (coproc_requested_ram_bytes < OPENBUS_COPROC_RAM_MIN) {
		return OPENBUS_COPROC_RAM_MIN;
	}
	if (max != 0 && coproc_requested_ram_bytes > max) {
		return max;
	}
	return coproc_requested_ram_bytes;
}

int
openbus_coproc_fit(void)
{
	openbus_master master;
	uint32_t size;

	memset(&master, 0, sizeof(master));

	if ((int) coproc_requested_core < 0 ||
	    (int) coproc_requested_core >= COPROC_CORE_COUNT) {
		return -1;
	}
	master.name = coproc_cores[coproc_requested_core].card_name;

	/* Clamped to what the core can address, so a hand-edited setting cannot
	   ask a 6502 for memory it has no way to reach. */
	size = openbus_coproc_requested_ram();

	/*
	 * ★ REFUSE AN OCCUPIED SLOT BEFORE TOUCHING ANY STATE. openbus_fit() is
	 * what enforces one card per slot, and asking it last looks harmless
	 * until you notice what happens on the way: the lines below free the
	 * card's RAM and clear its state, so an earlier version of this function
	 * DESTROYED the working card that was about to refuse the request. Its
	 * register window then read as an empty slot. Found by
	 * tests/test_openbus_coproc.c, which asks for a second card on purpose.
	 */
	if (openbus_present()) {
		return -1;
	}

	/* Any memory from a previous fit goes first, so fitting twice cannot leak. */
	free(cp.ram);
	free(cp.ctl);
	memset(&cp, 0, sizeof(cp));

	cp.core = coproc_requested_core;
	cp.ram = calloc(size, 1);
	if (cp.ram == NULL) {
		return -1;
	}
	cp.ram_size = size;

	/* The card's own memory, which the core cannot see: the region table, the
	   write log and the latch pages live here rather than in the core's address
	   space. See openbus_coproc.h. */
	cp.ctl = calloc(OPENBUS_COPROC_CTL_SIZE, 1);
	if (cp.ctl == NULL) {
		free(cp.ram);
		cp.ram = NULL;
		cp.ram_size = 0;
		return -1;
	}
	cp.ctl_size = OPENBUS_COPROC_CTL_SIZE;
	cp.stop_reason = OPENBUS_COPROC_STOP_NONE;

	switch (cp.core) {
	case OPENBUS_COPROC_RV32I:
		rv32i_init(&cp.cpu.rv32i, cp.ram, cp.ram_size);
		break;
	case OPENBUS_COPROC_6502:
	case OPENBUS_COPROC_65C02:
		cpu6502_init(&cp.cpu.m6502, cp.ram, cp.ram_size);
		/* The only difference between the two cards: which part it is. */
		cpu6502_set_cmos(&cp.cpu.m6502,
		                 cp.core == OPENBUS_COPROC_65C02);
		break;
	case OPENBUS_COPROC_6809:
		cpu6809_init(&cp.cpu.m6809, cp.ram, cp.ram_size);
		break;
	case OPENBUS_COPROC_6800:
		cpu6800_init(&cp.cpu.m6800, cp.ram, cp.ram_size);
		break;
	case OPENBUS_COPROC_Z80:
	case OPENBUS_COPROC_8080:
		cpu_z80_init(&cp.cpu.z80, cp.ram, cp.ram_size);
		/* The only difference between the two cards: which part it is. An 8080
		   is not a Z80 with instructions removed - its flags differ too. See
		   the note on i8080 in cpu_z80.h. */
		cpu_z80_set_8080(&cp.cpu.z80, cp.core == OPENBUS_COPROC_8080);
		cp.cpu.z80.io_in = coproc_io_in;
		cp.cpu.z80.io_out = coproc_io_out;
		cp.cpu.z80.io_ctx = NULL;
		break;
	default:
		/* ★ Not a default that guesses. Every core is named above, so a core
		   added to the enum and forgotten here fails to fit rather than
		   silently coming up as some other processor. */
		free(cp.ctl);
		cp.ctl = NULL;
		cp.ctl_size = 0;
		free(cp.ram);
		cp.ram = NULL;
		cp.ram_size = 0;
		return -1;
	}

	/*
	 * The decode goes on after the core is initialised, and with no map set,
	 * so a card that is never told about regions behaves exactly as it did
	 * before any of this: every address is plain card RAM.
	 */
	copro_bus_init(&cp.bus, cp.ram, cp.ram_size, cp.ctl, cp.ctl_size);
	coproc_rehook();

	master.reg_read = coproc_reg_read;
	master.reg_write = coproc_reg_write;
	master.run = coproc_run;
	master.reset = coproc_reset;
	master.close = coproc_close;

	if (openbus_fit(&master) != 0) {
		free(cp.ram);
		cp.ram = NULL;
		cp.ram_size = 0;
		free(cp.ctl);
		cp.ctl = NULL;
		cp.ctl_size = 0;
		return -1;
	}

	return 0;
}
