/*
  RPCEmu - An Acorn system emulator

  Copyright (C) 2026 Andy Timmins

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
 */

#ifndef SUPPORT_FILES_H
#define SUPPORT_FILES_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * The guest-side files a release ships - expansion card modules, the podule
 * ROMs, the template CMOS - and keeping the copies in the data directory in
 * step with them.
 *
 * The problem this exists to solve: those files are versioned with the
 * emulator, but on Windows and Linux a release is one folder holding both the
 * program and the user's data, so somebody who keeps their folder across an
 * upgrade keeps the old modules with it. The emulator is new, the guest modules
 * are not, and nothing says so.
 *
 * The release therefore carries a manifest of what it shipped, and the data
 * directory carries a copy of the manifest it was last seeded from. Comparing
 * the two says what to bring over, and it says it without hashing anything at
 * startup: the recorded manifest is what the data directory was given, so if an
 * entry is unchanged there is nothing to do.
 *
 * A file the user has edited themselves is therefore left alone until the
 * release changes that same file, which is the behaviour somebody who edits a
 * module would want. A file they have deleted comes back, because a missing
 * file is a broken installation rather than a preference.
 *
 * Deliberately free of the filesystem and of wxWidgets: the decisions are made
 * here from stated inputs so they can be tested without either.
 */

/** Longest relative path this handles, e.g. "poduleroms/rpcemumonitor,ffa". */
#define SUPPORT_PATH_MAX	192

/** Hash as lower-case hex, with room for MD5 (32) or SHA-256 (64) and a NUL. */
#define SUPPORT_HASH_MAX	65

/** One file the release ships. */
typedef struct {
	char path[SUPPORT_PATH_MAX];	/**< Relative, '/' separated */
	char hash[SUPPORT_HASH_MAX];	/**< Lower-case hex, empty if unknown */
} SupportFile;

/**
 * Read a manifest.
 *
 * The format is deliberately close to what md5sum and shasum write, so it can
 * be generated by a two-line script and read by eye:
 *
 *     # comment
 *     version 1
 *     algorithm md5
 *     <hash>  poduleroms/hostfs,ffa
 *
 * Two spaces separate the hash from the path, and the rest of the line is the
 * path - RISC OS filenames contain commas and may contain spaces, so the path
 * is never split on whitespace.
 *
 * @param text   Manifest text, NUL terminated
 * @param out    Filled in with the entries, may be NULL to count only
 * @param max    Entries `out` can hold
 * @return Number of entries found, or -1 if the text is not a manifest at all
 *         (no version line). A count larger than `max` means `out` holds the
 *         first `max` and the rest were not stored.
 */
int support_manifest_parse(const char *text, SupportFile *out, int max);

/**
 * Which files have to be copied from the release into the data directory.
 *
 * An entry is copied when the release's hash for it differs from the one the
 * data directory recorded, or when the data directory never recorded it, or
 * when the file is not there at all.
 *
 * @param shipped        Entries from the release's manifest
 * @param shipped_count  How many
 * @param recorded       Entries from the data directory's manifest, may be NULL
 * @param recorded_count How many, 0 if there is no recorded manifest
 * @param exists         Answers whether the data directory holds this path;
 *                       may be NULL, in which case every file is assumed
 *                       present and only the hashes decide
 * @param ctx            Passed to `exists`
 * @param out            Filled in with pointers into `shipped`, may be NULL
 * @param max            Entries `out` can hold
 * @return Number of files needing to be copied, which may exceed `max`
 */
int support_files_plan(const SupportFile *shipped, int shipped_count,
                       const SupportFile *recorded, int recorded_count,
                       int (*exists)(const char *path, void *ctx), void *ctx,
                       const SupportFile **out, int max);

/**
 * Is this a path the manifest may name?
 *
 * Guards against a manifest - which on the network path would come from
 * outside - naming somewhere other than the directories this manages. Rejects
 * absolute paths, anything containing "..", backslashes, and any first
 * component that is not one of the managed directories.
 *
 * @return non-zero if the path is one this may write
 */
int support_path_is_safe(const char *path);

/*
 * Reported as each file goes in, so a window can say what is happening. `path`
 * is NULL on the final call, which says the run has finished.
 */
typedef void (*SupportInstallProgress)(int done, int total, const char *path,
                                       void *ctx);

/**
 * How many files would be brought over, without bringing any.
 *
 * For deciding whether to put a window on screen at all: on almost every
 * startup the answer is none, and a progress dialogue that flashes up for no
 * work is worse than no dialogue.
 *
 * @param datadir Data directory, with a trailing separator
 * @return Number of files that need copying
 */
int support_install_pending(const char *datadir);

/**
 * Bring the data directory's copies of the guest files up to date.
 *
 * @param datadir  Data directory, with a trailing separator
 * @param progress Called as it goes, may be NULL
 * @param ctx      Passed to `progress`
 * @return Number of files written
 */
int support_install_run(const char *datadir, SupportInstallProgress progress,
                        void *ctx);

#ifdef __cplusplus
}
#endif

#endif /* SUPPORT_FILES_H */
