#!/usr/bin/env python3
"""Generate the monitor definition this module carries, from display_mode.c.

The mode ladder is read out of src/display_mode.c rather than written down
again. The emulator's own menus are built from that table and, on RISC OS 5,
so is the synthesised EDID; a monitor definition listing anything different
would have the guest and the emulator disagree about the same machine, which is
a fault that has already had to be fixed once.

Timings are deliberately not honest. RPCEmu draws the display in software and
has no pixel clock at all, so the blanking intervals and the dot clock are
fiction - only the active pixel counts reach the screen. What the numbers DO
affect is whether RISC OS accepts the mode: VIDC20 has a bandwidth limit that
scales with depth, and a mode declared at a true 60Hz is refused at 16M colours
even when the framebuffer would fit several times over. Measured on RISC OS
3.71 with 8MB of VRAM: at a 60Hz dot clock 1024x768 was refused at 64K colours
(1.5MB); at the low clock below, 1920x1080 at 16M colours (7.9MB) is accepted
and only 1920x1200 (8.8MB) is refused, which is the VRAM running out and
nothing else.
"""
import re, sys, os

# Fixed blanking, matching the porches edid.c uses so both describe one monitor.
HS, HBP, HFP = 32, 80, 48
VS, VBP, VFP = 6, 29, 3
PIXEL_RATE = 25175      # kHz. See the note above: low on purpose.

# VIDC20 cannot scan out a display wider than this, so a mode above it does not
# belong in a definition describing what VIDC20 drives. Leaving them in is not
# merely useless: RISC OS 3.71 stops making sense of the file when it meets one,
# and the whole definition is lost - the symptom being a definition that loads
# with no error and changes nothing at all. The wider modes are still offered on
# RISC OS 5 through the graphics card, which is not VIDC20 and has no such
# limit.
VIDC20_MAX_WIDTH = 2048

def modes(path):
    src = open(path).read()
    body = src[src.index('display_modes[] = {'):]
    body = body[:body.index('};')]
    out = []
    for w, h in re.findall(r'\{\s*(\d+)\s*,\s*(\d+)\s*\}', body):
        if int(w) <= VIDC20_MAX_WIDTH:
            out.append((int(w), int(h)))
    return out

def mdf(ms):
    lines = ["# RPCEmu virtual monitor - generated, do not edit",
             "file_format:1", "monitor_title:RPCEmu", "DPMS_state:1", ""]
    for w, h in ms:
        lines += [f"# {w} x {h}", "startmode", f" mode_name:{w} x {h}",
                  f" x_res:{w}", f" y_res:{h}", f" pixel_rate:{PIXEL_RATE}",
                  f" h_timings:{HS},{HBP},0,{w},0,{HFP}",
                  f" v_timings:{VS},{VBP},0,{h},0,{VFP}",
                  " sync_pol:0", "endmode", ""]
    return "\n".join(lines) + "\n"        # RISC OS text files end lines with LF

def main():
    src, out = sys.argv[1], sys.argv[2]
    ms = modes(src)
    if not ms:
        sys.exit("mkmdf: no modes found in " + src)
    text = mdf(ms)
    with open(out, "w") as f:
        f.write("@ Generated by mkmdf.py from src/display_mode.c - do not edit.\n")
        f.write(f"@ {len(ms)} modes.\n\nmdf_text:\n")
        for line in text.split("\n")[:-1]:
            esc = line.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'\t.ascii\t"{esc}\\n"\n')
        f.write("mdf_end:\n\t.balign\t4, 0\n")
    print(f"mkmdf.py: {len(ms)} modes, {len(text)} bytes -> {os.path.basename(out)}")

main()
