#!/usr/bin/env python3
"""Generate the monitor definition this module carries, from display_mode.c.

The mode ladder is read out of src/display_mode.c rather than written down
again. The emulator's own menus are built from that table and, on RISC OS 5,
so is the synthesised EDID; a monitor definition listing anything different
would have the guest and the emulator disagree about the same machine, which is
a fault that has already had to be fixed once.

Timings are deliberately not honest. RPCEmu draws the display in software and
has no pixel clock at all, so the blanking intervals and the dot clock are
fiction - only the active pixel counts reach the screen. What the numbers DO
affect is whether RISC OS accepts the mode: VIDC20 has a bandwidth limit that
scales with depth, and a mode declared at a true 60Hz is refused at 16M colours
even when the framebuffer would fit several times over. Measured on RISC OS
3.71 with 8MB of VRAM: at a 60Hz dot clock 1024x768 was refused at 64K colours
(1.5MB); at the low clock below, 1920x1080 at 16M colours (7.9MB) is accepted
and only 1920x1200 (8.8MB) is refused, which is the VRAM running out and
nothing else.
"""
import re, sys, os

# Fixed blanking, matching the porches edid.c uses so both describe one monitor.
HS, HBP, HFP = 32, 80, 48
VS, VBP, VFP = 6, 29, 3
PIXEL_RATE = 25175      # kHz. See the note above: low on purpose.

# The widest mode a detailed timing can describe: build_detailed_timing() in
# edid.c carries 12 bits of horizontal active, so 4095, and the definition here
# describes the same monitor as that block.
#
# This used to be 2048, on the grounds that VIDC20 cannot scan out a wider
# display and that RISC OS 3.71 loses the whole definition when it meets one.
# Neither holds in this emulator, and the cap was the entire reason RISC OS 4
# could not reach the large modes - issue #207, where 3840x2160 in 256 colours
# was reported as working in 1.1.13 and not afterwards. The module first shipped
# in 1.1.16, which is the change the reporter was feeling.
#
# Measured on 29 August 2026 with the cap raised, both machines booting to a
# desktop and the mode read back from the framebuffer rather than believed:
#
#   RISC OS 4.39, 16MB VRAM   1920x1440, 2560x1440 and 3840x2160 all accepted
#   RISC OS 3.71,  8MB VRAM   the same, and 3440x1440, at 256 colours
#
# 3.71 keeps its definition throughout - 1152x864, 1600x1200 and 1920x1440 still
# select afterwards - so the definition is not being discarded. RPCEmu draws the
# display in software and has no VIDC20 scan-out limit to hit.
#
# What still bounds a mode is the framestore, which RISC OS checks for itself,
# and the depth: 3840x2160 is 8MB at 256 colours and 33MB at 16M, so the deeper
# modes simply are not offered at that size. That is the trade, and it is the
# user's to make.
MAX_WIDTH = 4096

def modes(path):
    src = open(path).read()
    body = src[src.index('display_modes[] = {'):]
    body = body[:body.index('};')]
    out = []
    for w, h in re.findall(r'\{\s*(\d+)\s*,\s*(\d+)\s*\}', body):
        if int(w) <= MAX_WIDTH:
            out.append((int(w), int(h)))
    return out

def mdf(ms):
    lines = ["# RPCEmu virtual monitor - generated, do not edit",
             "file_format:1", "monitor_title:RPCEmu", "DPMS_state:1", ""]
    for w, h in ms:
        lines += [f"# {w} x {h}", "startmode", f" mode_name:{w} x {h}",
                  f" x_res:{w}", f" y_res:{h}", f" pixel_rate:{PIXEL_RATE}",
                  f" h_timings:{HS},{HBP},0,{w},0,{HFP}",
                  f" v_timings:{VS},{VBP},0,{h},0,{VFP}",
                  " sync_pol:0", "endmode", ""]
    return "\n".join(lines) + "\n"        # RISC OS text files end lines with LF

def main():
    src, out = sys.argv[1], sys.argv[2]
    ms = modes(src)
    if not ms:
        sys.exit("mkmdf: no modes found in " + src)
    text = mdf(ms)
    with open(out, "w") as f:
        f.write("@ Generated by mkmdf.py from src/display_mode.c - do not edit.\n")
        f.write(f"@ {len(ms)} modes.\n\nmdf_text:\n")
        for line in text.split("\n")[:-1]:
            esc = line.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'\t.ascii\t"{esc}\\n"\n')
        f.write("mdf_end:\n\t.balign\t4, 0\n")
    print(f"mkmdf.py: {len(ms)} modes, {len(text)} bytes -> {os.path.basename(out)}")

main()
